# Generated by Django 4.0.5 on 2022-06-11 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(blank=True, max_length=255, null=True)),
                ('C_address', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Fax', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('C_Web', models.CharField(blank=True, max_length=255, null=True)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('C_image', models.ImageField(blank=True, null=True, upload_to='c_logo')),
                ('Create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
