# Generated by Django 4.0.5 on 2022-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='Page_lod_img',
            field=models.ImageField(blank=True, null=True, upload_to='page_load_img'),
        ),
    ]
