# Generated by Django 4.0.5 on 2022-06-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_userprofilem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileM',
        ),
    ]
