# Generated by Django 4.0.5 on 2022-06-13 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0004_delete_userprofilem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('B_name', models.CharField(blank=True, max_length=255, null=True)),
                ('B_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('B_address', models.CharField(blank=True, max_length=255, null=True)),
                ('B_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('B_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('B_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
